name: Code Coverage Report
description: Comments a pull request with the code coverage
author: Romeo Van Snick
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  pr_number:
    descirption: Number of the Pull Request
    required: true

runs:
  using: node12
  main: dist/main.js
